using System.Buffers;
using System.Collections.Immutable;
using System.IO.Pipelines;
using System.Text.Json;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.DependencyInjection;

namespace MinimalHtml.Vite;

/// <summary>
/// A resolver for Vite manifest files. This class is responsible for reading the Vite manifest file, caching the results, and providing methods to retrieve asset information and write import maps. The manifest file is expected to be in JSON format and should contain information about the assets generated by Vite, including their file paths, integrity hashes, and any imports or dependencies. The resolver also supports caching the manifest data in memory and invalidating the cache when the manifest file changes, allowing for efficient retrieval of asset information without needing to read the file on every request.
/// </summary>
public static class ViteManifestExtensions
{
    /// <summary>
    /// Registers the Vite manifest resolver and related services in the dependency injection container. This method adds a singleton instance of the <see cref="ViteManifestResolver"/> to the service collection, which is responsible for reading and caching the Vite manifest file. It also registers delegates for retrieving asset information and writing import maps, which can be injected into other services or used directly in endpoints. The method takes optional parameters for the manifest path and import map path, allowing for customization of where the manifest file is located and whether an import map should be used. By default, it looks for the manifest file at ".vite/manifest.json" relative to the web root.
    /// </summary>
    /// <param name="services"></param>
    /// <param name="manifestPath"></param>
    /// <param name="importmapPath"></param>
    /// <returns></returns>
    public static IServiceCollection RegisterViteAssets(this IServiceCollection services, string? manifestPath = null, string? importmapPath = null) =>
        services.AddSingleton(s => new ViteManifestResolver(
            manifestPath ?? ViteManifestResolver.DefaultRelativeManifestPath,
            importmapPath,
            s.GetRequiredService<IWebHostEnvironment>(),
            s.GetRequiredService<IMemoryCache>()))
        .AddSingleton<GetAsset>(s => s.GetRequiredService<ViteManifestResolver>().GetAsset)
        .AddSingleton<WriteImportMap>(s => s.GetRequiredService<ViteManifestResolver>().WriteImportMap);
}

/// <summary>
/// A resolver for Vite manifest files. This class is responsible for reading the Vite manifest file, caching the results, and providing methods to retrieve asset information and write import maps. The manifest file is expected to be in JSON format and should contain information about the assets generated by Vite, including their file paths, integrity hashes, and any imports or dependencies. The resolver also supports caching the manifest data in memory and invalidating the cache when the manifest file changes, allowing for efficient retrieval of asset information without needing to read the file on every request.
/// </summary>
/// <param name="writer"></param>
/// <returns></returns>
public delegate ValueTask<FlushResult> WriteImportMap(PipeWriter writer);

/// <summary>
/// A resolver for Vite manifest files. This class is responsible for reading the Vite manifest file, caching the results, and providing methods to retrieve asset information and write import maps. The manifest file is expected to be in JSON format and should contain information about the assets generated by Vite, including their file paths, integrity hashes, and any imports or dependencies. The resolver also supports caching the manifest data in memory and invalidating the cache when the manifest file changes, allowing for efficient retrieval of asset information without needing to read the file on every request.
/// </summary>
/// <param name="manifestPath"></param>
/// <param name="importmapPath"></param>
/// <param name="env"></param>
/// <param name="cache"></param>
public class ViteManifestResolver(string manifestPath, string? importmapPath, IWebHostEnvironment env, IMemoryCache cache)
{
    private static readonly SemaphoreSlim s_semaphore = new(1, 1);
    internal const string DefaultRelativeManifestPath = ".vite/manifest.json";

    /// <summary>
    /// Retrieves asset information for a given asset ID from the Vite manifest. This method checks the cache for the asset information and returns it if available. If the asset information is not in the cache, it reads the manifest file, parses the JSON content, and extracts the relevant information to create an <see cref="Asset"/> instance. The method also handles any imports or dependencies associated with the asset, ensuring that all related assets are retrieved and included in the result. If the specified asset ID is not found in the manifest, it returns an <see cref="Asset"/> instance with a null URL and no imports.
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    public async ValueTask<Asset> GetAsset(string id)
    {
        var assets = await GetAssetsCached();
        var trimmed = id.TrimStart('~', '/');
        return assets.TryGetValue(trimmed, out var found)
            ? found
            : new Asset(trimmed, null, []);
    }

    /// <summary>
    /// Writes the import map to the provided <see cref="PipeWriter"/>. This method retrieves the import map content from the specified import map path, caches it for efficient retrieval, and writes it to the <see cref="PipeWriter"/> in the appropriate format for inclusion in an HTML document. If the import map file is not found or is empty, it writes an empty script tag with the correct type attribute. This allows for dynamic inclusion of the import map in HTML responses without needing to read the file on every request, while also ensuring that any changes to the import map file are reflected in subsequent responses due to cache invalidation based on file changes.
    /// </summary>
    /// <param name="writer"></param>
    /// <returns></returns>
    public async ValueTask<FlushResult> WriteImportMap(PipeWriter writer)
    {
        var bytes = await GetImportmapBytesCached(CancellationToken.None);
        if (bytes.Length <= 0) return new();
        writer.Write("""<script type="importmap">"""u8);
        writer.Write(bytes);
        writer.Write("""</script>"""u8);
        return new();
    }

    private async Task<byte[]> GetImportmapBytesCached(CancellationToken token)
    {
        if (string.IsNullOrWhiteSpace(importmapPath)) return [];
        if (cache.TryGetValue<byte[]>(importmapPath, out var value) && value is { }) return value;
        await s_semaphore.WaitAsync(token);
        try
        {
            if (cache.TryGetValue(importmapPath, out value) && value is { }) return value;
            value = await GetImportmapBytesUncached(token);
            var expirationToken = env.WebRootFileProvider.Watch(importmapPath);
            cache.Set(importmapPath, value, expirationToken);
            return value;
        }
        finally
        {
            s_semaphore.Release();
        }
    }

    private async Task<byte[]> GetImportmapBytesUncached(CancellationToken token)
    {
        if (string.IsNullOrWhiteSpace(importmapPath)) return [];
        var path = env.WebRootFileProvider.GetFileInfo(importmapPath);
        if (path == null) return [];
        await using var stream = path.CreateReadStream();
        await using var mem = new MemoryStream();
        await stream.CopyToAsync(mem, token);
        return mem.ToArray();
    }

    private async ValueTask<ImmutableDictionary<string, Asset>> GetAssetsCached()
    {
        if (cache.TryGetValue<ImmutableDictionary<string, Asset>>(manifestPath, out var value) && value is { }) return value;
        await s_semaphore.WaitAsync();
        try
        {
            if (cache.TryGetValue(manifestPath, out value) && value is { }) return value;
            value = await GetAssets();
            var token = env.WebRootFileProvider.Watch(manifestPath);
            cache.Set(manifestPath, value, expirationToken: token);
            return value;
        }
        finally
        {
            s_semaphore.Release();
        }
    }

    private async ValueTask<ImmutableDictionary<string, Asset>> GetAssets()
    {
        var result = new Dictionary<string, Asset>();
        var importDict = new Dictionary<string, Asset>();
        var path = env.WebRootFileProvider.GetFileInfo(manifestPath);
        if (path is null) return ImmutableDictionary<string, Asset>.Empty;
        await using var file = path.CreateReadStream();
        using var doc = await JsonDocument.ParseAsync(file);

        var props = doc.RootElement.EnumerateObject().ToDictionary(x => x.Name, x => x.Value);

        while (props.Count > 0)
        {
            var first = props.FirstOrDefault();
            props.Remove(first.Key);
            var isEntry = first.Value.TryGetProperty("isEntry"u8, out var e) && e.GetBoolean();
            var src = first.Value.GetProperty("file"u8).GetString() ?? first.Key;
            var integrity = first.Value.TryGetProperty("integrity"u8, out var integrityProp) ? integrityProp.GetString() : null;
            Asset asset;
            if (first.Key.EndsWith(".module.css") == true)
            {
                asset = HandleImports(first.Value)[0];
            }
            else
            {
                asset = new Asset(Assets.TrimUrl(src), integrity, HandleImports(first.Value));
            }
            importDict[first.Key] = asset;
            if (isEntry || (!src.EndsWith(".js") && !src.EndsWith(".css")))
            {
                result[first.Key] = asset;
            }
        }

        return result.ToImmutableDictionary();

        ImmutableArray<Asset> HandleImports(JsonElement element)
        {
            var list = new List<Asset>();
            if (element.TryGetProperty("imports"u8, out var imports))
            {
                foreach (var import in imports.EnumerateArray())
                {
                    if(import.GetString() is { } importKey)
                    {
                        list.Add(GetImport(importKey));
                    }
                }
            }
            if (element.TryGetProperty("assets"u8, out imports))
            {
                foreach (var import in imports.EnumerateArray())
                {
                    if(import.GetString() is { } importKey)
                    {
                        list.Add(GetImport(importKey));
                    }
                }
            }
            if (element.TryGetProperty("css"u8, out imports))
            {
                foreach (var import in imports.EnumerateArray())
                {
                    if(import.GetString() is { } importKey)
                    {
                        list.Add(GetImport(importKey));
                    }
                }
            }
            return [.. list];
        }

        Asset GetImport(string importKey)
        {
            if (importDict.TryGetValue(importKey, out var importedAsset))
            {
                return importedAsset;
            }

            if (props.TryGetValue(importKey, out var import))
            {
                var file = import.TryGetProperty("file", out var fileProp)
                    ? fileProp.GetString() ?? importKey
                    : importKey;
                var integrity = import.TryGetProperty("integrity"u8, out var integrityProp) ? integrityProp.GetString() : null;
                importedAsset = new Asset(Assets.TrimUrl(file), integrity, HandleImports(import));
                props.Remove(importKey);
                var isEntry = import.TryGetProperty("isEntry"u8, out var e) && e.GetBoolean();
                if (isEntry)
                {
                    result[importKey] = importedAsset;
                }
            }
            else
            {
                importedAsset = new Asset(Assets.TrimUrl(importKey), null, []);
            }

            importDict[importKey] = importedAsset;
            return importedAsset;
        }
    }
}
