on:
  pull_request:
      branches: [main]
      paths-ignore:
        - "**/*.md"
        - "**/*.gitignore"
        - "**/*.gitattributes"
        - "**/sample.yaml"
  workflow_dispatch:
  push:
    branches:
      - main
    tags: ["v*.*.*"]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true

    steps:
    - uses: actions/checkout@v4
    
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x.x
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore -p:SourceRevisionId=$GITHUB_SHA -p:ContinuousIntegrationBuild=true

    - name: Test
      run: dotnet test --configuration Release --no-restore --no-build

    - name: Get version from tag
      id: get_version
      uses: jannemattila/get-version-from-tag@v4

    - name: Display version
      run: echo "Version: ${{ steps.get_version.outputs.version }}"

    - name: Pack (ci)
      run: dotnet pack --configuration Release --output ./artifacts/ci --verbosity normal -p:SourceRevisionId=$GITHUB_SHA -p:Version=${{ steps.get_version.outputs.version }} -p:ContinuousIntegrationBuild=true  --no-restore --no-build


    - name: Publish Package (ci)
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      run: |
        for file in ./artifacts/ci/*.nupkg; do
          dotnet nuget push "$file" -s "NUGET" -k ${{ secrets.NUGET_API_KEY }}
        done