on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  my-job:
    name: push
    runs-on: ubuntu-latest
    environment: Bunny
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./samples/MinimalHtml.Sample/Dockerfile
          push: true
          tags: "flixcor/minimalhtml-sample:latest,flixcor/minimalhtml-sample:${{ github.sha }}"
          cache-from: type=registry,ref=flixcor/minimalhtml-sample:buildcache
          cache-to: type=registry,ref=flixcor/minimalhtml-sample:buildcache,mode=max
          platforms: linux/amd64,linux/arm64
          build-args: |
            REVISION=${{ github.sha }}

      - name: update container image on Magic Containers
        uses: BunnyWay/actions/container-update-image@main
        with:
          app_id: ${{ secrets.APP_ID }}
          api_key: ${{ secrets.BUNNYNET_API_KEY }}
          container: Sample
          image_tag: "${{ github.sha }}"
